import 'package:my_digital_guide/page/artefect_list.dart';

class Constants {
  static List<Artefact> artefacts = [
    Artefact(name: '3c Steam Locomotive essay', collection: 'Postage', location: 'Mail Room', description: '''As the railway’s became an important integration in American culture, various post offices used steam locomotives as the cover for their stamps.''', imageUrl:"https://ids.si.edu/ids/deliveryService?max_w=800&id=NPM-260305_152_56_2a"),
    Artefact(name: '3c Steam Locomotive re-issue single', collection: 'Postage', location: 'Mail Room', description: '''Used postage stamp featuring a steam locomotive.''', imageUrl:"https://ids.si.edu/ids/deliveryService?max_w=800&id=NPM-1980_2493_0592"),
    Artefact(name: '3c Steam Locomotive G Grill single', collection: 'Postage', location: 'Mail Room', description: '''Alternative stamp cover featuring a single grill steam locomotive.''', imageUrl:"https://ids.si.edu/ids/deliveryService?max_w=800&id=NPM-1980_2493_0547"),
    Artefact(name: 'Canadian Pacific Railway Owney tag', collection: 'Symbols & Signage', location: 'Sign section', description: '''Owney occasionally traveled on Canadian railways, including the eastern portion of the Canadian Pacific Railroad. This baggage token, marked “Special P. 2847” was given to Owney during one of his trips on that railroad. The “Special” marking was used for travelers whose baggage would follow their journey off of the main railway onto another line. Railroad companies had agreements to return these specially marked tokens to the railroad of origin.''', imageUrl:"https://ids.si.edu/ids/deliveryService?max_w=800&id=NPM-0_052985_49e"),
    Artefact(name: 'Railway Mail Service Superintendent Owney tag', collection: 'Symbols & Signage', location: 'Sign section', description: '''Owney’s best friends among postal employees were the railway mail clerks who rode with him on trains. While in Boston, Massachusetts, Owney often spent time visiting not only the general city post office, but also the Railway Mail Service offices. At the time of this visit, the Division Superintendent of the RMS for Boston was Edward J. Ryan, who had started his career as a railway mail service clerk in 1868, riding the Boston and Albany Railway Post Office for \$1,400 a year. The pride of the Railway Mail Service workers is evident in their boast of being “First in Everything” on this tag.''', imageUrl:"https://ids.si.edu/ids/deliveryService?max_w=800&id=NPM-0_052985_148e"),
    Artefact(name: '''Baltimore and Grafton Railway Owney tag''', collection: 'Symbols & Signage', location: 'Sign section', description: '''This horseshoe-shaped metal tag includes the inscription that it was presented to “His Dogship by F.M.Parker.” The reverse of the tag includes the date April 20, 1892, and the railway line, the Baltimore and Grafton Railway Post Office (RPO) car. ''', imageUrl:"https://ids.si.edu/ids/deliveryService?max_w=800&id=NPM-0_052985_110e"),
    Artefact(name: '''Chesapeake & Ohio Railway Owney tag''', collection: 'Symbols & Signage', location: 'Sign section', description: '''Owney received this baggage check token while traveling along the Chesapeake & Ohio Railway. The “local” marking indicates that the tag was meant for use on the main line, not for someone traveling onto another railway line. The tag was manufactured by Edmund Hoole’s Manufacturing Company of New York City. ''', imageUrl:"https://www.si.edu/object/chesapeake-ohio-railway-owney-tag:npm_0.052985.244"),
  ];
}