// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOnInzuxulb7q6Nj-9FkR6KenEh0sJDPI',
    appId: '1:370707943934:web:f03a25aee2a157939eb0af',
    messagingSenderId: '370707943934',
    projectId: 'mydigitalguide',
    authDomain: 'mydigitalguide.firebaseapp.com',
    storageBucket: 'mydigitalguide.appspot.com',
    measurementId: 'G-G7R9XCEB6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJFH5K81TeB37lVSkErGufTX9c5evC2T4',
    appId: '1:370707943934:android:3292365f80af16079eb0af',
    messagingSenderId: '370707943934',
    projectId: 'mydigitalguide',
    storageBucket: 'mydigitalguide.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbAb2bEbcLBAYaZ0FWBC5i7rH5wOKZ2u4',
    appId: '1:370707943934:ios:b2d0c995f643b6d99eb0af',
    messagingSenderId: '370707943934',
    projectId: 'mydigitalguide',
    storageBucket: 'mydigitalguide.appspot.com',
    iosClientId: '370707943934-lf918ptdbi75ag7j9dsmqo4lu4d03hea.apps.googleusercontent.com',
    iosBundleId: 'com.nisarg.myDigitalGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbAb2bEbcLBAYaZ0FWBC5i7rH5wOKZ2u4',
    appId: '1:370707943934:ios:b2d0c995f643b6d99eb0af',
    messagingSenderId: '370707943934',
    projectId: 'mydigitalguide',
    storageBucket: 'mydigitalguide.appspot.com',
    iosClientId: '370707943934-lf918ptdbi75ag7j9dsmqo4lu4d03hea.apps.googleusercontent.com',
    iosBundleId: 'com.nisarg.myDigitalGuide',
  );
}
